.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge-Solution-NonMem-Fn - Debug ]----------"
	@cd "D:\cPP\CodeLite\cpp-training-codelite\Section14\Challenge-Solution-NonMem-Fn\Challenge-Solution-NonMem-Fn" && "$(MAKE)" -f  "Challenge-Solution-NonMem-Fn.mk"
clean:
	@echo "----------Cleaning project:[ Challenge-Solution-NonMem-Fn - Debug ]----------"
	@cd "D:\cPP\CodeLite\cpp-training-codelite\Section14\Challenge-Solution-NonMem-Fn\Challenge-Solution-NonMem-Fn" && "$(MAKE)" -f  "Challenge-Solution-NonMem-Fn.mk" clean
