.PHONY: clean All

All:
	@echo "----------Building project:[ Mystring-operator-methods - Debug ]----------"
	@cd "D:\cPP\CodeLite\cpp-training-codelite\Section14\Mystring-operator-methods\Mystring-operator-methods" && "$(MAKE)" -f  "Mystring-operator-methods.mk"
clean:
	@echo "----------Cleaning project:[ Mystring-operator-methods - Debug ]----------"
	@cd "D:\cPP\CodeLite\cpp-training-codelite\Section14\Mystring-operator-methods\Mystring-operator-methods" && "$(MAKE)" -f  "Mystring-operator-methods.mk" clean
