.PHONY: clean All

All:
	@echo "----------Building project:[ Mystring-insertion-extraction - Debug ]----------"
	@cd "D:\cPP\CodeLite\cpp-training-codelite\Section14\Mystring-insertion-extraction\Mystring-insertion-extraction" && "$(MAKE)" -f  "Mystring-insertion-extraction.mk"
clean:
	@echo "----------Cleaning project:[ Mystring-insertion-extraction - Debug ]----------"
	@cd "D:\cPP\CodeLite\cpp-training-codelite\Section14\Mystring-insertion-extraction\Mystring-insertion-extraction" && "$(MAKE)" -f  "Mystring-insertion-extraction.mk" clean
