.PHONY: clean All

All:
	@echo "----------Building project:[ ChallengeWithRawPointer - Debug ]----------"
	@cd "D:\cPP\CodeLite\cpp-training-codelite\Section13\ChallengeWithRawPointer\ChallengeWithRawPointer" && "$(MAKE)" -f  "ChallengeWithRawPointer.mk"
clean:
	@echo "----------Cleaning project:[ ChallengeWithRawPointer - Debug ]----------"
	@cd "D:\cPP\CodeLite\cpp-training-codelite\Section13\ChallengeWithRawPointer\ChallengeWithRawPointer" && "$(MAKE)" -f  "ChallengeWithRawPointer.mk" clean
