.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge - Debug ]----------"
	@cd "D:\cPP\CodeLite\cpp-training-codelite\Section13\Challenge\Challenge" && "$(MAKE)" -f  "Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Challenge - Debug ]----------"
	@cd "D:\cPP\CodeLite\cpp-training-codelite\Section13\Challenge\Challenge" && "$(MAKE)" -f  "Challenge.mk" clean
