.PHONY: clean All

All:
	@echo "----------Building project:[ StaticClassMembers - Debug ]----------"
	@cd "D:\cPP\CodeLite\cpp-training-codelite\Section13\StaticClassMembers\StaticClassMembers" && "$(MAKE)" -f  "StaticClassMembers.mk"
clean:
	@echo "----------Cleaning project:[ StaticClassMembers - Debug ]----------"
	@cd "D:\cPP\CodeLite\cpp-training-codelite\Section13\StaticClassMembers\StaticClassMembers" && "$(MAKE)" -f  "StaticClassMembers.mk" clean
