.PHONY: clean All

All:
	@echo "----------Building project:[ MoveConstructor - Debug ]----------"
	@cd "D:\cPP\CodeLite\cpp-training-codelite\Section13\MoveConstructor\MoveConstructor" && "$(MAKE)" -f  "MoveConstructor.mk"
clean:
	@echo "----------Cleaning project:[ MoveConstructor - Debug ]----------"
	@cd "D:\cPP\CodeLite\cpp-training-codelite\Section13\MoveConstructor\MoveConstructor" && "$(MAKE)" -f  "MoveConstructor.mk" clean
